[package]
name = "wait"
version = "2.6.0"
authors = ["ufoscout <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
port_check = "0.1"

[dev-dependencies]
atomic-counter = "1.0"
lazy_static = "1.3"
time = "0.1.40"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
#panic = 'abort'