name: Rust

on:  
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - "x86_64"
    #      - "aarch64"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-musl
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.arch }}-unknown-linux-musl
          use-cross: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.arch }}-unknown-linux-musl/release/wait