name: Rust

on:  
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch:
          - { name: x86_64, target: x86_64-unknown-linux-musl }
          - { name: aarch64, target: aarch64-unknown-linux-musl }
          - { name: armv7, target: armv7-unknown-linux-musleabihf }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.arch.target }}
          use-cross: true
      - name: Copy and prepare default artifact for release
        if: matrix.arch.name == 'x86_64'
        run: |
            mkdir -p target/artifacts
            cp "target/${{ matrix.arch.target }}/release/wait" "target/artifacts/wait"
      - name: Copy and prepare all artifacts for release
        run: |
            mkdir -p target/artifacts
            cp "target/${{ matrix.arch.target }}/release/wait" "target/artifacts/wait_${{ matrix.arch.name }}"
            echo "Artifacts list:"
            ls -latr target/artifacts/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/artifacts/*